# ****** Properties for < Back-annotate Pin Locations > *********
# ****** Properties for < Behavioral Check Syntax > *********
project set "Use Custom Project File" "false" -process "Behavioral Check Syntax"
# ****** Properties for < Check Syntax > *********
# ****** Properties for < Create Schematic Symbol > *********
project set "Overwrite Existing Symbol" "true" -process "Create Schematic Symbol"
# ****** Properties for < Generate IBIS Model > *********
project set "Disable Detailed Package Model Insertion" "false" -process "Generate IBIS Model"
project set "Maximum Signal Name Length" "20" -process "Generate IBIS Model"
project set "Output File Name" "ildr_signal" -process "Generate IBIS Model"
project set "Show All Models" "false" -process "Generate IBIS Model"
project set "VCCAUX Voltage Level" "2.5V" -process "Generate IBIS Model"
# ****** Properties for < Generate Post-Map Simulation Model > *********
project set "Automatically Insert glbl Module in the Netlist" "true" -process "Generate Post-Map Simulation Model"
project set "Bring Out Global Set/Reset Net as a Port" "false" -process "Generate Post-Map Simulation Model"
project set "Bring Out Global Tristate Net as a Port" "false" -process "Generate Post-Map Simulation Model"
project set "Device Speed Grade/Select ABS Minimum" "-3" -process "Generate Post-Map Simulation Model"
project set "Do Not Escape Signal and Instance Names in Netlist" "false" -process "Generate Post-Map Simulation Model"
project set "Generate Architecture Only (No Entity Declaration)" "false" -process "Generate Post-Map Simulation Model"
project set "Generate Multiple Hierarchical Netlist Files" "false" -process "Generate Post-Map Simulation Model"
project set "Generate Testbench File" "false" -process "Generate Post-Map Simulation Model"
project set "Global Set/Reset Port Name" "GSR_PORT" -process "Generate Post-Map Simulation Model"
project set "Global Tristate Port Name" "GTS_PORT" -process "Generate Post-Map Simulation Model"
project set "Include 'uselib Directive in Verilog File" "false" -process "Generate Post-Map Simulation Model"
project set "Include SIMPRIM Models in Verilog File" "false" -process "Generate Post-Map Simulation Model"
project set "Include sdf_annotate task in Verilog File" "true" -process "Generate Post-Map Simulation Model"
project set "Output Extended Identifiers" "false" -process "Generate Post-Map Simulation Model"
project set "Path Used in sdf_annotate task" "Default" -process "Generate Post-Map Simulation Model"
project set "Rename Design Instance in Testbench File to" "UUT" -process "Generate Post-Map Simulation Model"
project set "Rename Top Level Architecture To" "Structure" -process "Generate Post-Map Simulation Model"
project set "Rename Top Level Entity to" "ildr_signal" -process "Generate Post-Map Simulation Model"
project set "Reset On Configuration Pulse Width" "100" -process "Generate Post-Map Simulation Model"
project set "Retain Hierarchy" "true" -process "Generate Post-Map Simulation Model"
project set "Simulation Model Target" "VHDL" -process "Generate Post-Map Simulation Model"
project set "Tristate On Configuration Pulse Width" "0" -process "Generate Post-Map Simulation Model"
# ****** Properties for < Generate Post-Map Static Timing > *********
project set "Change Device Speed To" "-3" -process "Generate Post-Map Static Timing"
project set "Generate Constraints Interaction Report" "false" -process "Generate Post-Map Static Timing"
project set "Generate Datasheet Section" "true" -process "Generate Post-Map Static Timing"
project set "Generate Timegroups Section" "false" -process "Generate Post-Map Static Timing"
project set "Number of Paths in Error/Verbose Report" "3" -process "Generate Post-Map Static Timing"
project set "Perform Advanced Analysis" "false" -process "Generate Post-Map Static Timing"
project set "Report Fastest Path(s) in Each Constraint" "true" -process "Generate Post-Map Static Timing"
project set "Report Paths by Endpoint" "3" -process "Generate Post-Map Static Timing"
project set "Report Type" "Verbose Report" -process "Generate Post-Map Static Timing"
# ****** Properties for < Generate Post-Place & Route Simulation Model > *********
project set "Automatically Insert glbl Module in the Netlist" "true" -process "Generate Post-Place & Route Simulation Model"
project set "Bring Out Global Set/Reset Net as a Port" "false" -process "Generate Post-Place & Route Simulation Model"
project set "Bring Out Global Tristate Net as a Port" "false" -process "Generate Post-Place & Route Simulation Model"
project set "Device Speed Grade/Select ABS Minimum" "-3" -process "Generate Post-Place & Route Simulation Model"
project set "Do Not Escape Signal and Instance Names in Netlist" "false" -process "Generate Post-Place & Route Simulation Model"
project set "Generate Architecture Only (No Entity Declaration)" "false" -process "Generate Post-Place & Route Simulation Model"
project set "Generate Multiple Hierarchical Netlist Files" "false" -process "Generate Post-Place & Route Simulation Model"
project set "Generate Testbench File" "false" -process "Generate Post-Place & Route Simulation Model"
project set "Global Set/Reset Port Name" "GSR_PORT" -process "Generate Post-Place & Route Simulation Model"
project set "Global Tristate Port Name" "GTS_PORT" -process "Generate Post-Place & Route Simulation Model"
project set "Include 'uselib Directive in Verilog File" "false" -process "Generate Post-Place & Route Simulation Model"
project set "Include SIMPRIM Models in Verilog File" "false" -process "Generate Post-Place & Route Simulation Model"
project set "Include sdf_annotate task in Verilog File" "true" -process "Generate Post-Place & Route Simulation Model"
project set "Insert Buffers to Prevent Pulse Swallowing" "true" -process "Generate Post-Place & Route Simulation Model"
project set "Output Extended Identifiers" "false" -process "Generate Post-Place & Route Simulation Model"
project set "Path Used in sdf_annotate task" "Default" -process "Generate Post-Place & Route Simulation Model"
project set "Rename Design Instance in Testbench File to" "UUT" -process "Generate Post-Place & Route Simulation Model"
project set "Rename Top Level Architecture To" "Structure" -process "Generate Post-Place & Route Simulation Model"
project set "Rename Top Level Entity to" "ildr_signal" -process "Generate Post-Place & Route Simulation Model"
project set "Reset On Configuration Pulse Width" "100" -process "Generate Post-Place & Route Simulation Model"
project set "Retain Hierarchy" "true" -process "Generate Post-Place & Route Simulation Model"
project set "Simulation Model Target" "VHDL" -process "Generate Post-Place & Route Simulation Model"
project set "Tristate On Configuration Pulse Width" "0" -process "Generate Post-Place & Route Simulation Model"
# ****** Properties for < Generate Post-Place & Route Static Timing > *********
project set "Change Device Speed To" "-3" -process "Generate Post-Place & Route Static Timing"
project set "Generate Constraints Interaction Report" "false" -process "Generate Post-Place & Route Static Timing"
project set "Generate Datasheet Section" "true" -process "Generate Post-Place & Route Static Timing"
project set "Generate Timegroups Section" "false" -process "Generate Post-Place & Route Static Timing"
project set "Number of Paths in Error/Verbose Report" "3" -process "Generate Post-Place & Route Static Timing"
project set "Perform Advanced Analysis" "false" -process "Generate Post-Place & Route Static Timing"
project set "Report Fastest Path(s) in Each Constraint" "true" -process "Generate Post-Place & Route Static Timing"
project set "Report Paths by Endpoint" "3" -process "Generate Post-Place & Route Static Timing"
project set "Report Type" "Verbose Report" -process "Generate Post-Place & Route Static Timing"
# ****** Properties for < Generate Post-Synthesis Simulation Model > *********
project set "Automatically Insert glbl Module in the Netlist" "true" -process "Generate Post-Synthesis Simulation Model"
project set "Do Not Escape Signal and Instance Names in Netlist" "false" -process "Generate Post-Synthesis Simulation Model"
project set "Generate Architecture Only (No Entity Declaration)" "false" -process "Generate Post-Synthesis Simulation Model"
project set "Generate Multiple Hierarchical Netlist Files" "false" -process "Generate Post-Synthesis Simulation Model"
project set "Generate Testbench File" "false" -process "Generate Post-Synthesis Simulation Model"
project set "Include 'uselib Directive in Verilog File" "false" -process "Generate Post-Synthesis Simulation Model"
project set "Include UNISIM Models in Verilog File" "false" -process "Generate Post-Synthesis Simulation Model"
project set "Output Extended Identifiers" "false" -process "Generate Post-Synthesis Simulation Model"
project set "Rename Design Instance in Testbench File to" "UUT" -process "Generate Post-Synthesis Simulation Model"
project set "Rename Top Level Architecture To" "Structure" -process "Generate Post-Synthesis Simulation Model"
project set "Rename Top Level Entity to" "ildr_signal" -process "Generate Post-Synthesis Simulation Model"
project set "Retain Hierarchy" "true" -process "Generate Post-Synthesis Simulation Model"
project set "Simulation Model Target" "VHDL" -process "Generate Post-Synthesis Simulation Model"
# ****** Properties for < Generate Post-Translate Simulation Model > *********
project set "Automatically Insert glbl Module in the Netlist" "true" -process "Generate Post-Translate Simulation Model"
project set "Bring Out Global Set/Reset Net as a Port" "false" -process "Generate Post-Translate Simulation Model"
project set "Bring Out Global Tristate Net as a Port" "false" -process "Generate Post-Translate Simulation Model"
project set "Do Not Escape Signal and Instance Names in Netlist" "false" -process "Generate Post-Translate Simulation Model"
project set "Generate Architecture Only (No Entity Declaration)" "false" -process "Generate Post-Translate Simulation Model"
project set "Generate Multiple Hierarchical Netlist Files" "false" -process "Generate Post-Translate Simulation Model"
project set "Generate Testbench File" "false" -process "Generate Post-Translate Simulation Model"
project set "Global Set/Reset Port Name" "GSR_PORT" -process "Generate Post-Translate Simulation Model"
project set "Global Tristate Port Name" "GTS_PORT" -process "Generate Post-Translate Simulation Model"
project set "Include 'uselib Directive in Verilog File" "false" -process "Generate Post-Translate Simulation Model"
project set "Include SIMPRIM Models in Verilog File" "false" -process "Generate Post-Translate Simulation Model"
project set "Output Extended Identifiers" "false" -process "Generate Post-Translate Simulation Model"
project set "Rename Design Instance in Testbench File to" "UUT" -process "Generate Post-Translate Simulation Model"
project set "Rename Top Level Architecture To" "Structure" -process "Generate Post-Translate Simulation Model"
project set "Rename Top Level Entity to" "ildr_signal" -process "Generate Post-Translate Simulation Model"
project set "Reset On Configuration Pulse Width" "100" -process "Generate Post-Translate Simulation Model"
project set "Retain Hierarchy" "true" -process "Generate Post-Translate Simulation Model"
project set "Simulation Model Target" "VHDL" -process "Generate Post-Translate Simulation Model"
project set "Tristate On Configuration Pulse Width" "0" -process "Generate Post-Translate Simulation Model"
# ****** Properties for < Generate Programming File > *********
project set "Allow SelectMAP Pins to Persist" "false" -process "Generate Programming File"
project set "Configuration Pin Done" "Pull Up" -process "Generate Programming File"
project set "Configuration Pin Program" "Pull Up" -process "Generate Programming File"
project set "Configuration Rate" "2" -process "Generate Programming File"
project set "Create ASCII Configuration File" "false" -process "Generate Programming File"
project set "Create Binary Configuration File" "false" -process "Generate Programming File"
project set "Create Bit File" "true" -process "Generate Programming File"
project set "Create IEEE 1532 Configuration File" "false" -process "Generate Programming File"
project set "Create Logic Allocation File" "false" -process "Generate Programming File"
project set "Create Mask File" "false" -process "Generate Programming File"
project set "Create ReadBack Data Files" "false" -process "Generate Programming File"
project set "Done (Output Events)" "Default (4)" -process "Generate Programming File"
project set "Drive Awake Pin During Suspend/Wake Sequence" "false" -process "Generate Programming File"
project set "Drive Done Pin High" "false" -process "Generate Programming File"
project set "Enable BitStream Compression" "false" -process "Generate Programming File"
project set "Enable Cyclic Redundancy Checking (CRC)" "true" -process "Generate Programming File"
project set "Enable Debugging of Serial Mode BitStream" "false" -process "Generate Programming File"
project set "Enable External Master Clock" "false" -process "Generate Programming File"
project set "Enable Internal Done Pipe" "false" -process "Generate Programming File"
project set "Enable Multi-Pin Wake-Up Suspend Mode" "false" -process "Generate Programming File"
project set "Enable Outputs (Output Events)" "Default (5)" -process "Generate Programming File"
project set "Enable Suspend/Wake Global Set/Reset" "false" -process "Generate Programming File"
project set "Encrypt Bitstream" "false" -process "Generate Programming File"
project set "Encrypt Key Select" "BBRAM" -process "Generate Programming File"
project set "Essential Bits" "false" -process "Generate Programming File"
project set "FPGA Start-Up Clock" "CCLK" -process "Generate Programming File"
project set "GTS Cycle During Suspend/Wakeup Sequence" "4" -process "Generate Programming File"
project set "GWE Cycle During Suspend/Wakeup Sequence" "5" -process "Generate Programming File"
project set "JTAG Pin TCK" "Pull Up" -process "Generate Programming File"
project set "JTAG Pin TDI" "Pull Up" -process "Generate Programming File"
project set "JTAG Pin TDO" "Pull Up" -process "Generate Programming File"
project set "JTAG Pin TMS" "Pull Up" -process "Generate Programming File"
project set "Mask Pins for Multi-Pin Wake-Up Suspend Mode" "0x00" -process "Generate Programming File"
project set "MultiBoot: Insert IPROG CMD in the Bitfile" "Enable" -process "Generate Programming File"
project set "MultiBoot: Next Configuration Mode" "001" -process "Generate Programming File"
project set "MultiBoot: Starting Address for Golden Configuration" "0x00000000" -process "Generate Programming File"
project set "MultiBoot: Starting Address for Next Configuration" "0x00000000" -process "Generate Programming File"
project set "MultiBoot: Use New Mode for Next Configuration" "true" -process "Generate Programming File"
project set "MultiBoot: User-Defined Register for Failsafe Scheme" "0x0000" -process "Generate Programming File"
project set "Place MultiBoot Settings into Bitstream" "false" -process "Generate Programming File"
project set "Release Write Enable (Output Events)" "Default (6)" -process "Generate Programming File"
project set "Retry Configuration if CRC Error Occurs" "false" -process "Generate Programming File"
project set "Run Design Rules Checker (DRC)" "true" -process "Generate Programming File"
project set "Security" "Enable Readback and Reconfiguration" -process "Generate Programming File"
project set "Set SPI Configuration Bus Width" "1" -process "Generate Programming File"
project set "Setup External Master Clock Division" "1" -process "Generate Programming File"
project set "Unused IOB Pins" "Pull Down" -process "Generate Programming File"
project set "UserID Code (8 Digit Hexadecimal)" "0xFFFFFFFF" -process "Generate Programming File"
project set "Wait for DCM and PLL Lock (Output Events)" "Default (NoWait)" -process "Generate Programming File"
project set "Wakeup Clock" "Startup Clock" -process "Generate Programming File"
project set "Watchdog Timer Value" "0xFFFF" -process "Generate Programming File"
# ****** Properties for < Generate Text Power Report > *********
project set "Analysis Effort Level" "Standard" -process "Generate Text Power Report"
project set "Load Physical Constraints File" "Default" -process "Generate Text Power Report"
project set "Load Simulation File" "Default" -process "Generate Text Power Report"
project set "Maximum Number of Lines in Report" "1000" -process "Generate Text Power Report"
project set "Produce Verbose Report" "false" -process "Generate Text Power Report"
# ****** Properties for < Implement Design > *********
project set "Allow Logic Optimization Across Hierarchy" "false" -process "Implement Design"
project set "Allow Unexpanded Blocks" "false" -process "Implement Design"
project set "Allow Unmatched LOC Constraints" "false" -process "Implement Design"
project set "Allow Unmatched Timing Group Constraints" "false" -process "Implement Design"
project set "Automatically Insert glbl Module in the Netlist" "true" -process "Implement Design"
project set "Bring Out Global Set/Reset Net as a Port" "false" -process "Implement Design"
project set "Bring Out Global Tristate Net as a Port" "false" -process "Implement Design"
project set "Change Device Speed To" "-3" -process "Implement Design"
project set "Combinatorial Logic Optimization" "true" -process "Implement Design"
project set "Create I/O Pads from Ports" "false" -process "Implement Design"
project set "Device Speed Grade/Select ABS Minimum" "-3" -process "Implement Design"
project set "Do Not Escape Signal and Instance Names in Netlist" "false" -process "Implement Design"
project set "Enable Multi-Threading" "2" -process "Implement Design"
project set "Equivalent Register Removal" "true" -process "Implement Design"
project set "Extra Cost Tables" "0" -process "Implement Design"
project set "Extra Effort (Highest PAR level only)" "Normal" -process "Implement Design"
project set "Generate Architecture Only (No Entity Declaration)" "false" -process "Implement Design"
project set "Generate Asynchronous Delay Report" "false" -process "Implement Design"
project set "Generate Clock Region Report" "false" -process "Implement Design"
project set "Generate Constraints Interaction Report" "false" -process "Implement Design"
project set "Generate Datasheet Section" "true" -process "Implement Design"
project set "Generate Detailed MAP Report" "false" -process "Implement Design"
project set "Generate Multiple Hierarchical Netlist Files" "false" -process "Implement Design"
project set "Generate Post-Place & Route Power Report" "false" -process "Implement Design"
project set "Generate Post-Place & Route Simulation Model" "false" -process "Implement Design"
project set "Generate Testbench File" "false" -process "Implement Design"
project set "Generate Timegroups Section" "false" -process "Implement Design"
project set "Global Optimization" "Speed" -process "Implement Design"
project set "Global Set/Reset Port Name" "GSR_PORT" -process "Implement Design"
project set "Global Tristate Port Name" "GTS_PORT" -process "Implement Design"
project set "Ignore User Timing Constraints" "false" -process "Implement Design"
project set "Include 'uselib Directive in Verilog File" "false" -process "Implement Design"
project set "Include SIMPRIM Models in Verilog File" "false" -process "Implement Design"
project set "Include sdf_annotate task in Verilog File" "true" -process "Implement Design"
project set "Insert Buffers to Prevent Pulse Swallowing" "true" -process "Implement Design"
project set "LUT Combining" "Off" -process "Implement Design"
project set "Map Slice Logic into Unused Block RAMs" "false" -process "Implement Design"
project set "Maximum Compression" "false" -process "Implement Design"
project set "Netlist Translation Type" "Timestamp" -process "Implement Design"
project set "Number of Paths in Error/Verbose Report" "3" -process "Implement Design"
project set "Other Map Command Line Options" "-detail" -process "Implement Design"
project set "Output Extended Identifiers" "false" -process "Implement Design"
project set "Pack I/O Registers/Latches into IOBs" "Off" -process "Implement Design"
project set "Path Used in sdf_annotate task" "Default" -process "Implement Design"
project set "Perform Advanced Analysis" "false" -process "Implement Design"
project set "Place & Route Effort Level (Overall)" "High" -process "Implement Design"
project set "Place And Route Mode" "Route Only" -process "Implement Design"
project set "Placer Effort Level" "High" -process "Implement Design"
project set "Placer Extra Effort" "Normal" -process "Implement Design"
project set "Power Reduction" "Off" -process "Implement Design"
project set "Register Duplication" "Off" -process "Implement Design"
project set "Register Ordering" "8" -process "Implement Design"
project set "Rename Design Instance in Testbench File to" "UUT" -process "Implement Design"
project set "Rename Top Level Architecture To" "Structure" -process "Implement Design"
project set "Report Fastest Path(s) in Each Constraint" "true" -process "Implement Design"
project set "Report Paths by Endpoint" "3" -process "Implement Design"
project set "Report Type" "Verbose Report" -process "Implement Design"
project set "Reset On Configuration Pulse Width" "100" -process "Implement Design"
project set "Retain Hierarchy" "true" -process "Implement Design"
project set "Simulation Model Target" "VHDL" -process "Implement Design"
project set "Starting Placer Cost Table (1-100)" "1" -process "Implement Design"
project set "Timing Mode" "Performance Evaluation" -process "Implement Design"
project set "Trim Unconnected Signals" "true" -process "Implement Design"
project set "Tristate On Configuration Pulse Width" "0" -process "Implement Design"
project set "Use LOC Constraints" "true" -process "Implement Design"
project set "Use RLOC Constraints" "Yes" -process "Implement Design"
# ****** Properties for < Map > *********
project set "Allow Logic Optimization Across Hierarchy" "false" -process "Map"
project set "Combinatorial Logic Optimization" "true" -process "Map"
project set "Enable Multi-Threading" "2" -process "Map"
project set "Equivalent Register Removal" "true" -process "Map"
project set "Extra Cost Tables" "0" -process "Map"
project set "Generate Detailed MAP Report" "false" -process "Map"
project set "Global Optimization" "Speed" -process "Map"
project set "Ignore User Timing Constraints" "false" -process "Map"
project set "LUT Combining" "Off" -process "Map"
project set "Map Slice Logic into Unused Block RAMs" "false" -process "Map"
project set "Maximum Compression" "false" -process "Map"
project set "Other Map Command Line Options" "-detail" -process "Map"
project set "Pack I/O Registers/Latches into IOBs" "Off" -process "Map"
project set "Placer Effort Level" "High" -process "Map"
project set "Placer Extra Effort" "Normal" -process "Map"
project set "Power Reduction" "Off" -process "Map"
project set "Register Duplication" "Off" -process "Map"
project set "Register Ordering" "8" -process "Map"
project set "Starting Placer Cost Table (1-100)" "1" -process "Map"
project set "Timing Mode" "Performance Evaluation" -process "Map"
project set "Trim Unconnected Signals" "true" -process "Map"
project set "Use RLOC Constraints" "Yes" -process "Map"
# ****** Properties for < Place & Route > *********
project set "Enable Multi-Threading" "4" -process "Place & Route"
project set "Extra Effort (Highest PAR level only)" "Normal" -process "Place & Route"
project set "Generate Asynchronous Delay Report" "false" -process "Place & Route"
project set "Generate Clock Region Report" "false" -process "Place & Route"
project set "Generate Post-Place & Route Power Report" "false" -process "Place & Route"
project set "Generate Post-Place & Route Simulation Model" "false" -process "Place & Route"
project set "Ignore User Timing Constraints" "false" -process "Place & Route"
project set "Place & Route Effort Level (Overall)" "High" -process "Place & Route"
project set "Place And Route Mode" "Route Only" -process "Place & Route"
project set "Power Reduction" "false" -process "Place & Route"
project set "Timing Mode" "Performance Evaluation" -process "Place & Route"
# ****** Properties for < Synthesize - XST > *********
project set "Add I/O Buffers" "true" -process "Synthesize - XST"
project set "Asynchronous To Synchronous" "false" -process "Synthesize - XST"
project set "Automatic BRAM Packing" "false" -process "Synthesize - XST"
project set "BRAM Utilization Ratio" "100" -process "Synthesize - XST"
project set "Bus Delimiter" "<>" -process "Synthesize - XST"
project set "Case" "Maintain" -process "Synthesize - XST"
project set "Case Implementation Style" "None" -process "Synthesize - XST"
project set "Cross Clock Analysis" "false" -process "Synthesize - XST"
project set "DSP Utilization Ratio" "100" -process "Synthesize - XST"
project set "Equivalent Register Removal" "true" -process "Synthesize - XST"
project set "FSM Encoding Algorithm" "Auto" -process "Synthesize - XST"
project set "FSM Style" "LUT" -process "Synthesize - XST"
project set "Generate RTL Schematic" "Yes" -process "Synthesize - XST"
project set "Global Optimization Goal" "AllClockNets" -process "Synthesize - XST"
project set "Hierarchy Separator" "/" -process "Synthesize - XST"
project set "Keep Hierarchy" "Yes" -process "Synthesize - XST"
project set "LUT Combining" "Auto" -process "Synthesize - XST"
project set "LUT-FF Pairs Utilization Ratio" "100" -process "Synthesize - XST"
project set "Max Fanout" "100000" -process "Synthesize - XST"
project set "Move First Flip-Flop Stage" "true" -process "Synthesize - XST"
project set "Move Last Flip-Flop Stage" "true" -process "Synthesize - XST"
project set "Netlist Hierarchy" "As Optimized" -process "Synthesize - XST"
project set "Number of Clock Buffers" "16" -process "Synthesize - XST"
project set "Optimization Effort" "High" -process "Synthesize - XST"
project set "Optimization Goal" "Speed" -process "Synthesize - XST"
project set "Optimize Instantiated Primitives" "false" -process "Synthesize - XST"
project set "Pack I/O Registers into IOBs" "No" -process "Synthesize - XST"
project set "Power Reduction" "false" -process "Synthesize - XST"
project set "RAM Extraction" "true" -process "Synthesize - XST"
project set "RAM Style" "Auto" -process "Synthesize - XST"
project set "ROM Extraction" "true" -process "Synthesize - XST"
project set "ROM Style" "Auto" -process "Synthesize - XST"
project set "Read Cores" "true" -process "Synthesize - XST"
project set "Reduce Control Sets" "Auto" -process "Synthesize - XST"
project set "Register Balancing" "Yes" -process "Synthesize - XST"
project set "Register Duplication" "true" -process "Synthesize - XST"
project set "Resource Sharing" "true" -process "Synthesize - XST"
project set "Safe Implementation" "No" -process "Synthesize - XST"
project set "Shift Register Extraction" "true" -process "Synthesize - XST"
project set "Shift Register Minimum Size" "2" -process "Synthesize - XST"
project set "Use Clock Enable" "Auto" -process "Synthesize - XST"
project set "Use DSP Block" "Auto" -process "Synthesize - XST"
project set "Use Synchronous Reset" "Auto" -process "Synthesize - XST"
project set "Use Synchronous Set" "Auto" -process "Synthesize - XST"
project set "Use Synthesis Constraints File" "true" -process "Synthesize - XST"
project set "Work Directory" "./xst" -process "Synthesize - XST"
project set "Write Timing Constraints" "false" -process "Synthesize - XST"
# ****** Properties for < Translate > *********
project set "Allow Unexpanded Blocks" "false" -process "Translate"
project set "Allow Unmatched LOC Constraints" "false" -process "Translate"
project set "Allow Unmatched Timing Group Constraints" "false" -process "Translate"
project set "Create I/O Pads from Ports" "false" -process "Translate"
project set "Netlist Translation Type" "Timestamp" -process "Translate"
project set "Use LOC Constraints" "true" -process "Translate"
