#!/bin/sh

# Copyright (c) 2024-2026 ufw workers, All rights reserved.
#
# Terms for redistribution and use can be found in LICENCE.

. "${MICROFRAMEWORK_ROOT:-../..}"/bin/tap.sh

canrun () {
    test -e ufw && test -e zephyr
}

logged_mmh () {
    mmh --log-to-file
}

plan 1
tap -p canrun logged_mmh 'Build minimal mmh system with ufw as a zephyr module'
