if(__UFW_DetectMonolith)
  return()
endif()
set(__UFW_DetectMonolith 1)

function(DetectMonolith)
  set(pwd ${ARGV0})
  if (NOT DEFINED pwd)
    set(pwd ${PROJECT_SOURCE_DIR})
  endif()
  get_filename_component(realpwd "${pwd}" REALPATH)
  if ("${realpwd}" STREQUAL "/")
    set(UFW_IN_MONOLITH 0 PARENT_SCOPE)
    message("-- Build does NOT appear to be in monolith environment.")
  else()
    if ((EXISTS "${realpwd}/ufw") AND
        (EXISTS "${realpwd}/.gitignore") AND
        (EXISTS "${realpwd}/test") AND
        (EXISTS "${realpwd}/test/libtap") AND
        (EXISTS "${realpwd}/test/googletest"))
      set(UFW_IN_MONOLITH 1 PARENT_SCOPE)
      set(UFW_MONOLITH_ROOT "${realpwd}" PARENT_SCOPE)
      message("-- Build monolith root: ${realpwd}")
    else()
      DetectMonolith("${realpwd}/..")
      if (DEFINED UFW_MONOLITH_ROOT)
        set(UFW_MONOLITH_ROOT ${UFW_MONOLITH_ROOT} PARENT_SCOPE)
      endif()
      if (DEFINED UFW_IN_MONOLITH)
        set(UFW_IN_MONOLITH ${UFW_IN_MONOLITH} PARENT_SCOPE)
      endif()
    endif()
  endif()
endfunction()

macro(MaybeSetupGoogleTest)
  if ((DEFINED UFW_IN_MONOLITH) AND (${UFW_IN_MONOLITH} EQUAL 1))
    set(GTEST_ROOT "${UFW_MONOLITH_ROOT}/test/googletest/build/googlemock/gtest")
    message("-- Setting GTEST_ROOT: ${GTEST_ROOT}")
  else()
    message("-- Could not setup GTEST_ROOT")
  endif()
endmacro()

macro(MaybeSetupGoogleTestTap)
  if ((DEFINED UFW_IN_MONOLITH) AND (${UFW_IN_MONOLITH} EQUAL 1))
    set(GTESTTAP_ROOT "${UFW_MONOLITH_ROOT}/test/gtest-tap-listener")
    message("-- Setting GTEST_ROOT: ${GTEST_ROOT}")
  else()
    message("-- Could not setup GTEST_ROOT")
  endif()
endmacro()
