if(__UFW_GNUCompilerWarnings)
  return()
endif()
set(__UFW_GNUCompilerWarnings 1)

include(CheckCCompilerFlag)
include(CheckCXXCompilerFlag)

macro(GNUCCompilerWarnings)
  check_c_compiler_flag(-Wall UFW_CC_HAS_Wall)
  check_c_compiler_flag(-Wextra UFW_CC_HAS_Wextra)
  check_c_compiler_flag(-Werror UFW_CC_HAS_Werror)
  check_c_compiler_flag(-Wasm UFW_CC_HAS_Wasm)
  check_c_compiler_flag(-Wimplicit-fallthrough=3 UFW_CC_HAS_Wimplicit_fallthrough)
  check_c_compiler_flag(-Wimplicit-function-declaration UFW_CC_HAS_Wimplicit_function_declaration)
  check_c_compiler_flag(-Wmissing-prototypes UFW_CC_HAS_Wmissing_prototypes)
  check_c_compiler_flag(-Wnewline-eof UFW_CC_HAS_Wnewline_eof)
  check_c_compiler_flag(-Wpacked UFW_CC_HAS_Wpacked)
  check_c_compiler_flag(-Wpadded UFW_CC_HAS_Wpadded)
  check_c_compiler_flag(-Wpedantic UFW_CC_HAS_Wpedantic)
  check_c_compiler_flag(-Wredundant-decls UFW_CC_HAS_Wredundant_decls)
  check_c_compiler_flag(-Wsequence-point UFW_CC_HAS_Wsequence_point)
  check_c_compiler_flag(-Wshadow UFW_CC_HAS_Wshadow)
  check_c_compiler_flag(-Wshift-sign-overflow UFW_CC_HAS_Wshift_sign_overflow)
  check_c_compiler_flag(-Wstrict-prototypes UFW_CC_HAS_Wstrict_prototypes)
  check_c_compiler_flag(-Wundef UFW_CC_HAS_Wundef)
  check_c_compiler_flag(-Wused-but-marked-unused UFW_CC_HAS_Wused_but_marked_unused)
endmacro()

macro(GNUCXXCompilerWarnings)
  check_cxx_compiler_flag(-Wall UFW_CXX_HAS_Wall)
  check_cxx_compiler_flag(-Wextra UFW_CXX_HAS_Wextra)
  check_cxx_compiler_flag(-Werror UFW_CXX_HAS_Werror)
  check_cxx_compiler_flag(-Wasm UFW_CXX_HAS_Wasm)
  check_cxx_compiler_flag(-Wimplicit-fallthrough=3 UFW_CXX_HAS_Wimplicit_fallthrough)
  check_cxx_compiler_flag(-Wnewline-eof UFW_CXX_HAS_Wnewline_eof)
  check_cxx_compiler_flag(-Wpacked UFW_CXX_HAS_Wpacked)
  check_cxx_compiler_flag(-Wpadded UFW_CXX_HAS_Wpadded)
  check_cxx_compiler_flag(-Wpedantic UFW_CXX_HAS_Wpedantic)
  check_cxx_compiler_flag(-Wredundant-decls UFW_CXX_HAS_Wredundant_decls)
  check_cxx_compiler_flag(-Wsequence-point UFW_CXX_HAS_Wsequence_point)
  check_cxx_compiler_flag(-Wshadow UFW_CXX_HAS_Wshadow)
  check_cxx_compiler_flag(-Wshift-sign-overflow UFW_CXX_HAS_Wshift_sign_overflow)
  check_cxx_compiler_flag(-Wundef UFW_CXX_HAS_Wundef)
  check_cxx_compiler_flag(-Wused-but-marked-unused UFW_CXX_HAS_Wused_but_marked_unused)
endmacro()
